export const CAMPOS = [
  {
    label: "Documento",
    prepend_icon: "mdi-card-account-details",
    type: 1,
    format: "number",
    name: "documento",
    model: null,
    required: true,
    error: "",
  },
  {
    label: "Nombres",
    prepend_icon: "mdi-account",
    type: 1,
    format: "text",
    name: "nombres",
    model: "",
    blank: true,
    error: "",
  },
  {
    label: "Apellidos",
    prepend_icon: "mdi-account",
    type: 1,
    format: "text",
    name: "apellidos",
    model: "",
    blank: true,
    error: "",
  },
  {
    label: "Correo",
    prepend_icon: "mdi-email",
    type: 1,
    format: "email",
    name: "correo",
    model: "",
  },
  {
    label: "Celular",
    prepend_icon: "mdi-phone",
    type: 1,
    format: "number",
    name: "celular",
    model: "",
  },
  {
    label: "Dirección",
    prepend_icon: "mdi-home",
    type: 1,
    format: "text",
    name: "direccion",
    model: "",
  },
  {
    label: "Género",
    prepend_icon: "mdi-gender-male-female-variant",
    type: 6,
    items: ["Masculino", "Femenino", "Otro"],
    name: "genero",
    model: "",
  },
  {
    label: "Fecha de nacimiento",
    prepend_icon: "mdi-cake",
    type: 1,
    format: "date",
    name: "fecha_nacimiento",
    model: "",
  },
  {
    label: "Estado",
    prepend_icon: "mdi-list-status",
    type: 6,
    items: ["Activo", "Inactivo", "Pendiente"],
    name: "estado",
    model: "",
  },
];
