export const FUNCIONES: any[] = [
  {
    tipo: 1,
    titulo: "Modulo de compras",
    color: "color_c",
  },
  { id: 1, tipo: 2, icono: "mdi-cart-plus", titulo: "Registro Compras" },
  { id: 2, tipo: 2, icono: "mdi-account-group", titulo: "Proveedores" },
  { id: 3, tipo: 2, icono: "mdi-cash-minus", titulo: "Cuentas por pagar" },
  {
    tipo: 1,
    titulo: "Modulo de ventas",
    color: "color_c",
  },
  { id: 4, tipo: 2, icono: "mdi-cash-plus", titulo: "Registro Ventas" },
  { id: 5, tipo: 2, icono: "mdi-account-group", titulo: "Clientes" },
  { id: 6, tipo: 2, icono: "mdi-cash-plus", titulo: "Cuentas por cobrar" },
  { id: 7, tipo: 2, icono: "mdi-currency-eth", titulo: "Movimientos" },
  {
    tipo: 1,
    titulo: "Modulo de inventario",
    color: "color_c",
  },
  { id: 8, tipo: 2, icono: "mdi-barcode", titulo: "Registro Productos" },
  { id: 9, tipo: 2, icono: "mdi-text-subject", titulo: "Categorias" },
  { id: 10, tipo: 2, icono: "mdi-text-short", titulo: "Marcas" },
  { id: 11, tipo: 2, icono: "mdi-warehouse", titulo: "Bodegas" },
  { id: 12, tipo: 2, icono: "mdi-share-all-outline", titulo: "Movimientos" },
  {
    tipo: 1,
    titulo: "Modulo de usuarios",
    color: "color_c",
  },
  {
    id: 13,
    tipo: 2,
    icono: "mdi-account-multiple",
    titulo: "Registro empleados",
  },
  {
    id: 14,
    tipo: 2,
    icono: "mdi-account-cog",
    titulo: "Actualizar empleados",
  },
  {
    id: 15,
    tipo: 2,
    icono: "mdi-cash-register",
    titulo: "Cajas",
  },
  {
    tipo: 1,
    titulo: "Modulo de pruebas",
    color: "color_c",
  },
  {
    id: 16,
    tipo: 2,
    icono: "mdi-bootstrap",
    titulo: "Movimientos",
  },
  {
    id: 17,
    tipo: 2,
    icono: "mdi-ticket-confirmation",
    titulo: "Comrpobantes",
  },
];
