export const CAMPOS = [
  {
    label: "Roles",
    prepend_icon: "mdi-calendar-week",
    type: 6,
    multiple: true,
    solo: false,
    items: ["Admin", "Empleado", "Provedor"],
    name: "rol",
    model: "",
    rules: "required",
  },
  {
    label: "Tipo documento",
    prepend_icon: "mdi-card-account-details",
    type: 6,
    multiple: false,
    solo: true,
    items: ["Cédula de ciudadania", "Tarjeta de identidad", "NIT"],
    name: "tipo_documento",
    model: "",
    rules: "required",
  },
  {
    label: "Documento",
    prepend_icon: "mdi-card-account-details",
    type: 1,
    format: "text",
    name: "documento",
    model: "",
    rules: "required|min:4|max:25",
  },
  {
    label: "Nombre/ Razon social",
    prepend_icon: "mdi-account",
    type: 1,
    multiple: false,
    solo: true,
    items: ["Carlos Díaz", "Edwin Valencia", "Cristhian Rosas", "Brayan Tobar"],
    name: "nombre_razon",
    model: "",
    rules: "required",
  },
  {
    label: "Apellidos",
    prepend_icon: "mdi-info",
    type: 1,
    name: "apellidos",
    model: "",
    multiple: true,
    rules: "required",
  },
  {
    label: "Fecha Nacimiento",
    prepend_icon: "mdi-info",
    type: 1,
    name: "fecha_nacimiento",
    model: "",
    multiple: true,
    rules: "required|min:5|max:1000",
  },
  {
    label: "Celular",
    prepend_icon: "mdi-phone",
    type: 1,
    format: "number",
    name: "celular",
    model: "",
  },
  {
    label: "Correo",
    prepend_icon: "mdi-email",
    type: 1,
    format: "email",
    name: "correo",
    model: "",
    rules: "email",
  },
  {
    label: "Género",
    prepend_icon: "mdi-gender-male-female-variant",
    type: 6,
    multiple: false,
    solo: true,
    items: ["Hombre", "Mujer", "Otro"],
    name: "genero",
    model: "",
    rules: "required",
  },
  {
    label: "Contrasena",
    prepend_icon: "mdi-email",
    type: 1,
    format: "password",
    name: "contrasena",
    model: "",
    rules: "email",
  },
  {
    label: "Estado",
    prepend_icon: "mdi-list-status",
    type: 6,
    multiple: false,
    solo: true,
    items: ["Activo", "Inactivo", "Pendiente"],
    name: "estado",
    model: "",
  },
];
